# Generated by Django 5.0 on 2023-12-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_movies_admin', '0002_alter_shows_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
