# Generated by Django 5.0 on 2023-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_movies_admin', '0003_movies_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_image',
            field=models.ImageField(blank=True, upload_to='movie_images/'),
        ),
    ]
