# Generated by Django 5.0 on 2023-12-29 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_my_movies_admin', '0005_alter_movies_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='show_time',
            field=models.TimeField(choices=[(datetime.time(11, 30), '11:30 AM'), (datetime.time(14, 30), '2:30 PM'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(21, 0), '9:00 PM')], max_length=8),
        ),
    ]
